export const TRANSLATIONS_AR = {
  "TRANSLATOR.SELECT": "اختر لغتك",
  "login.userName": "اسم المستخدم",
  "login.enter_userName": "ادخل اسم المستخدم",
  "login.password": "كلمة المرور",
  "login.enter_password": "ادخل كلمة المرور",
  "login.submit": "تسجيل",
  "login.userNameMissing": "ادخل اسم المستخدم",
  "login.passwordMissing": "ادخل كلمة المرور",
  "logout.button": "تسجيل الخروج",
  "user.userName": "اسم المستخدم",
  "user.nameAr": "الاسم (ع)",
  "user.nameEn": "الاسم(ج)",
  "user.password": "كلمة المرور",
  "user.isAdmin": "مدير النظام",
  "user.registerUser": "تسجيل مستخدم",
  "user.userList": "قائمة المستخدمين",
  "user.reset": "اعادة",
  "user.register.username.missing": "enter user name",
  "user.register.nameen.missing": "enter name en",
  "user.register.name.missing": "enter name ar",
  "user.register.password.missing": "enter password",
  "process.Completed": "اكتملت العملية بنجاح",
  "process.failed": "حدث خطأ",
};
