export const TRANSLATIONS_AR = {
  "TRANSLATOR.SELECT": "اختر لغتك",
  "login.userName": "اسم المستخدم",
  "login.enter_userName": "ادخل اسم المستخدم",
  "login.password": "كلمة المرور",
  "login.enter_password": "ادخل كلمة المرور",
  "login.submit": "تسجيل",
  "login.userNameMissing": "ادخل اسم المستخدم",
  "login.passwordMissing": "ادخل كلمة المرور",
  "logout.button": "تسجيل الخروج",
  "user.userName": "اسم المستخدم",
  "user.nameAr": "الاسم (ع)",
  "user.nameEn": "الاسم(ج)",
  "user.name": "الاسم",
  "user.password": "كلمة المرور",
  "user.isAdmin": "مدير النظام",
  "user.registerUser": "تسجيل مستخدم",
  "user.userList": "قائمة المستخدمين",
  "user.reset": "اعادة",
  "user.register.username.missing": "ادخل اسم المستخدم",
  "user.register.nameen.missing": "ادخل الاسم(ح)",
  "user.register.name.missing": "ادخل الاسم(ع)",
  "user.register.password.missing": "ادخل كلمة المرور",
  "process.Completed": "اكتملت العملية بنجاح",
  "process.failed": "حدث خطأ",
  CloseButton: "اغلاق",
  "user.Add": "اضافة",
  "user.Modify": "تعديل",
  "user.Delete": "حذف",
  "user.Premissions": "الصلاحيات",
  "connfirmDialog.yes": "نعم",
  "connfirmDialog.no": "لا",
  "connfirmDialog.are_You_Sure": "هل أنت متأكد؟",
  "premission.premissionName": "Name",
  "premission.EnableSave": "Save",
  "premission.EnableUpdate": "Update",
  "premission.EnableDelete": "Delete",
  "premission.EnableSearch": "Search",
  "premission.IsEnabledForTablet": "Tablet",
  "button.save": "Save",
  "button.reset": "Reset",
  "button.cancel": "Cancel",
  "setting.CompanyName": "اسم الشركة",
  "setting.Phone": "الهاتف",
  "setting.TextLogo": "نص الشعار",
  "setting.LogoImage64": "صورة الشعار",
  "setting.Save": "حفظ",
  "setting.reset": "اعادة",
  "unit.name": "الاسم",
  "unit.isDefault": "افتراضى",
  "unit.nameAr": "الاسم(ع)",
  "unit.nameEn": "الاسم(ح)",
  "unit.register.nameEn.missing": "ادخل الاسم(ح)",
  "unit.register.nameAr.missing": "ادخل الاسم(ع)",
  "entity.register": "تسجيل",
  "entity.reset": "اعادة",
};
