export const TRANSLATIONS_AR = {
  "TRANSLATOR.SELECT": "اختر لغتك",
  "login.userName": "اسم المستخدم",
  "login.enter_userName": "ادخل اسم المستخدم",
  "login.password": "كلمة المرور",
  "login.enter_password": "ادخل كلمة المرور",
  "login.submit": "تسجيل",
  "login.userNameMissing": "ادخل اسم المستخدم",
  "login.passwordMissing": "ادخل كلمة المرور",
  "logout.button": "تسجيل الخروج",
  "user.userName": "اسم المستخدم",
  "user.nameAr": "الاسم (ع)",
  "user.nameEn": "الاسم(ج)",
  "user.name": "الاسم",
  "user.password": "كلمة المرور",
  "user.isAdmin": "مدير النظام",
  "user.registerUser": "تسجيل مستخدم",
  "user.userList": "قائمة المستخدمين",
  "user.reset": "اعادة",
  "user.register.username.missing": "ادخل اسم المستخدم",
  "user.register.nameen.missing": "ادخل الاسم(ح)",
  "user.register.name.missing": "ادخل الاسم(ع)",
  "user.register.password.missing": "ادخل كلمة المرور",
  "process.Completed": "اكتملت العملية بنجاح",
  "process.failed": "حدث خطأ",
  CloseButton: "اغلاق",
  "user.Add": "اضافة",
  "user.Modify": "تعديل",
  "user.Delete": "حذف",
  "user.Premissions": "الصلاحيات",
};
