export const TRANSLATIONS_EN = {
  "TRANSLATOR.SELECT": "Select your language",
  "login.userName": "User Name",
  "login.enter_userName": "enter user name",
  "login.password": "password",
  "login.enter_password": "enter password",
  "login.submit": "submit",
  "login.userNameMissing": "enter user name",
  "login.passwordMissing": "enter password",
  "logout.button": "logout",
  "user.userName": "user Name",
  "user.nameAr": "Name(Ar)",
  "user.nameEn": "Name(En)",
  "user.name": "Name",
  "user.password": "password",
  "user.isAdmin": "is Admin",
  "user.registerUser": "Register User",
  "user.userList": "Users List",
  "user.reset": "Reset",
  "user.register.username.missing": "enter user name",
  "user.register.nameen.missing": "enter name en",
  "user.register.name.missing": "enter name ar",
  "user.register.password.missing": "enter password",
  "process.Completed": "process completed successfully",
  "process.failed": "error occurred",
  CloseButton: "Close",
  "user.Add": "Add",
  "user.Modify": "Modify",
  "user.Delete": "Delete",
  "user.Premissions": "Premissions",
  "connfirmDialog.yes": "Yes",
  "connfirmDialog.no": "No",
  "connfirmDialog.are_You_Sure": "Are You Sure?",
  "premission.premissionName": "Name",
  "premission.EnableSave": "Save",
  "premission.EnableUpdate": "Update",
  "premission.EnableDelete": "Delete",
  "premission.EnableSearch": "Search",
  "premission.IsEnabledForTablet": "Tablet",
  "button.save": "Save",
  "button.reset": "Reset",
  "button.cancel": "Cancel",
  "setting.CompanyName": "Company Name",
  "setting.Phone": "Phone",
  "setting.TextLogo": "Text Logo",
  "setting.LogoImage64": "Logo Image",
  "setting.Save": "Save",
  "setting.reset": "Reset",
  "unit.name": "Name",
  "unit.isDefault": "Default",
  "unit.nameAr": "Name Ar",
  "unit.nameEn": "Name En",
  "unit.register.nameAr.missing": "name ar is missing",
  "unit.register.nameEn.missing": "name en is missing",
  "entity.register": "Register",
  "entity.reset": "Reset",
};
