export const TRANSLATIONS_EN = {
  "TRANSLATOR.SELECT": "Select your language",
  "login.userName": "User Name",
  "login.enter_userName": "enter user name",
  "login.password": "password",
  "login.enter_password": "enter password",
  "login.submit": "submit",
  "login.userNameMissing": "enter user name",
  "login.passwordMissing": "enter password",
  "logout.button": "logout",
  "user.userName": "user Name",
  "user.nameAr": "Name(Ar)",
  "user.nameEn": "Name(En)",
  "user.password": "password",
  "user.isAdmin": "is Admin",
  "user.registerUser": "Register User",
  "user.userList": "Users List",
  "user.reset": "Reset",
  "user.register.username.missing": "enter user name",
  "user.register.nameen.missing": "enter name en",
  "user.register.name.missing": "enter name ar",
  "user.register.password.missing": "enter password",
};
